# all the logic for grammar checking is here
# generates a dependency tree, then DFS and check against predefined rules
# reports WHERE the error is and WHAT the error is and HOW to fix it
# relies on tree generated by dependency_parser.py
class EnglishGrammarChecker:
    def __init__(self, spacy_pipeline, input_text, rules):
        pass

    