# all the logic for grammar checking is here
# generates a dependency tree, then DFS and check against predefined rules
# reports WHERE the error is and WHAT the error is and HOW to fix it
# relies on tree generated by dependency_parser.py
class GrammarCheck:
    def __init__(self, model_path):
        pass

    def check(self, input_sentence, model_path):
        '''
        generates dependency tree from input sentence and checks against predefined rules
        return an error report
        '''

    def generate_tree(self, input_sentence, model_path):
        '''
        generates dependency tree from input sentence 
        '''
        pass

    def enforce(self, tree):
        '''
        DFS on tree and check against predefined rules
        '''
        pass

    def report(self, error_annotated_tree):
        '''
        return an error report based on tree annotated with errors
        '''
        pass

def test_grammar_check():
    pass